dummy: &dummy
  # name: dummy
  input:
    filename: events.csv
    line_skip: 0
  data:
    context:
      cpu_id: f
    start_events:
      - expected
    end_events:
      - real
  eva-selection:
    method: bmm
    block_size: 10
    threshold: 0.0001
  method: mixture3
  n_samples: 10000

generated: &generated
  name: generated
  input:
    filename: data/generated/events.csv
    line_skip: 1
    time_scaling: "us"
  data:
    # no context
    start_events:
      - a
    end_events:
      - d
  eva-selection:
    method: bmm
    block_size: 3
  model:
    method: mixture2
  simulation:
    n_samples: 1000

generated-recurring: &generated-recurring
  name: generated-recurring
  input:
    filename: data/generated-recurring/events.csv
    line_skip: 1
    time_scaling: "us"
  data:
    # no context
    start_events:
      - a
    end_events:
      - d
  eva-selection:
    method: bmm
    block_size: 3
  model:
    method: mixture2
  simulation:
    n_samples: 1000

cyclictest: &cyclictest
  name: cyclictest
  input:
    filename: data/cyclictest/events.csv
    line_skip: 0
    time_scaling: "ns"
  data:
    context:
      cpu: f
    start_events:
      - expected
    end_events:
      - real
  eva-selection:
    method: bmm
    block_size: 10
  model:
    method: mixture4
  simulation:
    n_samples: 10000

default:
  #<<: *generated
  #<<: *generated-recurring
  <<: *cyclictest
